### PR TITLE
Better greetings

### PR DESCRIPTION
**Pull request by mike-north**
I didn't test this code but my dog says it's fine

### CODE REVIEW

**Comment by mike-north** [comment]
@princeshekhar can you please take a look

**Comment by princevalluri** [comment]
Awesome change!

**Comment by jmkk** [comment]
LGTM too 👍 Publish!

**Review by jmkk — APPROVED** [review]

**Review by princevalluri — APPROVED** [review]

**Review by princevalluri — APPROVED** [review]

**Review by jmkk — APPROVED** [review]
Nice 👍👍👍https://media3.giphy.com/media/143vPc6b08locw/giphy.gif?cid=790b7611a1d4e84b4f844a6388dfa579d0765e2606c1fdd3&rid=giphy.gif

**Review by mike-north — COMMENTED** [review]
AAWDAWDA

**Pull request merged**
